runtime: nodejs10
env: standard

env_variables:
  "DATABASEURL": "mongodb+srv://singhpankaj079:Rj5AMPM%2E%2E@ashtanga-yoga-shala-s8cfb.mongodb.net/test?retryWrites=true&w=majority"
  "GOOGLE_APPLICATION_CREDENTIALS": "./ashtanga.json"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto