runtime: nodejs10
env: standard

env_variables:
  "DATABASEURL":
  "GOOGLE_APPLICATION_CREDENTIALS": "./ashtanga.json"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
